package:
  name: git-lfs
  version: 1.5.5

build:
  number: 0

source:
  fn: git-lfs-linux-amd64-1.5.5.tar.gz # [linux64]
  url: https://github.com/git-lfs/git-lfs/releases/download/v1.5.5/git-lfs-linux-amd64-1.5.5.tar.gz # [linux64]
  sha256: 910b2b5c158b238256087cae9b84cbc0bfb83c061d5b41161b79ca08cf61b2e8 # [linux64]
  fn: git-lfs-darwin-amd64-1.5.5.tar.gz # [osx]
  url: https://github.com/git-lfs/git-lfs/releases/download/v1.5.5/git-lfs-darwin-amd64-1.5.5.tar.gz # [osx]
  sha256: 2227668c76a07931dd387602f67c99d5d42f0a99c73b76f8949bbfe3a4cc49c7 # [osx]

requirements:
  run:
    - git

about:
  home: https://git-lfs.github.com/
  license: MIT
