#
# To build a Conda package, run conda build as:
#
#    conda build .
#
# To change a release to build, change the git_tag entry.
#

package:
  name: eups
  version: 2.0.2

build:
  number: 0
  string: 0

source:
  git_tag: 2.0.2
  git_url: https://github.com/RobertLuptonTheGood/eups

requirements:
  build:
    - python
    - "pip ==8.1.2"

  run:
    - python
    - "pip ==8.1.2"

about:
  home: http://github.com/RobertLuptonTheGood/eups
  license: GPLv2
  summary: A version manager tracking product dependencies
